# Generated by Django 4.1.6 on 2023-02-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
